export const actionTypes = {
  MERGE_STATE: 'SEARCH/MERGE_STATE',
  CLEAR_STATE: 'SEARCH/CLEAR_STATE',
  SET_SONG_LIST: 'SEARCH/SET_SONG_LIST',
  SET_SONG_COUNT: 'SEARCH/SET_SONG_COUNT',
  SET_ARTIST_LIST: 'SEARCH/SET_ARTIST_LIST',
  SET_ARTIST_COUNT: 'SEARCH/SET_ARTIST_COUNT',
  SET_ALBUM_LIST: 'SEARCH/SET_ALBUM_LIST',
  SET_ALBUM_COUNT: 'SEARCH/SET_ALBUM_COUNT',
  SET_SONGSHEET_LIST: 'SEARCH/SET_SONGSHEET_LIST',
  SET_SONGSHEET_COUNT: 'SEARCH/SET_SONGSHEET_COUNT',
  SET_MV_LIST: 'SEARCH/SET_MV_LIST',
  SET_MV_COUNT: 'SEARCH/SET_MV_COUNT',
  SET_SEARCH_SUGGEST: 'SEARCH/SET_SEARCH_SUGGEST',
  SET_IS_LOADING: 'SEARCH/SET_IS_LOADING'
}
