export const actionTypes = {
  MERGE_STATE: 'SONGSHEET/MERGE_STATE',
  CLEAR_STATE: 'SONGSHEET/CLEAR_STATE',
  SET_SONGSHEET_DETAIL: 'SONGSHEET/SET_SONGSHEET_DETAIL',
  SET_SONG_LIST: 'SONGSHEET/SET_SONG_LIST',
  SET_HOT_COMMENT_LIST: 'SONGSHEET/SET_HOT_COMMENT_LIST',
  SET_NEW_COMMENT_LIST: 'SONGSHEET/SET_NEW_COMMENT_LIST',
  SET_NEW_COMMENT_COUNT: 'SONGSHEET/SET_NEW_COMMENT_COUNT',
  SET_RELATED_SONGSHEET_LIST: 'SONGSHEET/SET_RELATED_SONGSHEET_LIST',
  SET_SONGSHEET_DETAIL_IS_LOADING: 'SONGSHEET/SET_SONGSHEET_DETAIL_IS_LOADING',
  SET_SONG_LIST_IS_LOADING: 'SONGSHEET/SET_SONG_LIST_IS_LOADING'
}
