export const actionTypes = {
  MERGE_STATE: 'PLAYER/MERGE_STATE',
  CLEAR_STATE: 'PLAYER/CLEAR_STATE',
  SET_SONG_LIST: 'PLAYER/SET_SONG_LIST',
  SET_LYRIC_LIST: 'PLAYER/SET_LYRIC_LIST',
  SET_CURRENT_INDEX: 'PLAYER/SET_CURRENT_INDEX',
  SET_CURRENT_ROW: 'PLAYER/SET_CURRENT_ROW',
  SET_AUDIO_STATUS: 'PLAYER/SET_AUDIO_STATUS',
  SET_MESSAGE_CONFIG: 'PLAYER/SET_MESSAGE_CONFIG'
}
