export const actionTypes = {
  MERGE_STATE: 'SONG/MERGE_STATE',
  CLEAR_STATE: 'SONG/CLEAR_STATE',
  SET_SONG_DETAIL: 'SONG/SET_SONG_DETAIL',
  SET_SONG_LYRIC: 'SONG/SET_SONG_LYRIC',
  SET_HOT_COMMENT_LIST: 'SONG/SET_HOT_COMMENT_LIST',
  SET_NEW_COMMENT_LIST: 'SONG/SET_NEW_COMMENT_LIST',
  SET_NEW_COMMENT_COUNT: 'SONG/SET_NEW_COMMENT_COUNT',
  SET_SIMI_SONGSHEET_LIST: 'SONG/SET_SIMI_SONGSHEET_LIST',
  SET_SIMI_SONG_LIST: 'SONG/SET_SIMI_SONG_LIST',
  SET_SONG_DETAIL_IS_LOADING: 'SONG/SET_SONG_DETAIL_IS_LOADING'
}
