export const actionTypes = {
  MERGE_STATE: 'DISCOVER_DJRADIO/MERGE_STATE',
  CLEAR_STATE: 'DISCOVER_DJRADIO/CLEAR_STATE',
  SET_CATE_LIST: 'DISCOVER_DJRADIO/SET_CATE_LIST',
  SET_RECOMD_RADIO_LIST: 'DISCOVER_DJRADIO/SET_RECOMD_RADIO_LIST',
  SET_HOT_RADIO_LIST: 'DISCOVER_DJRADIO/SET_HOT_RADIO_LIST',
  SET_HOT_RADIO_COUNT: 'DISCOVER_DJRADIO/SET_HOT_RADIO_COUNT',
  SET_HOT_RADIO_LIST_IS_LOADING: 'DISCOVER_DJRADIO/SET_HOT_RADIO_LIST_IS_LOADING'
}
