export const actionTypes = {
  MERGE_STATE: 'DISCOVER_ARTIST/MERGE_STATE',
  CLEAR_STATE: 'DISCOVER_ARTIST/CLEAR_STATE',
  SET_CAT_TITLE: 'DISCOVER_ARTIST/SET_CAT_TITLE',
  SET_ARTIST_LIST: 'DISCOVER_ARTIST/SET_ARTIST_LIST',
  SET_ARTIST_LIST_IS_LOADING: 'DISCOVER_ARTIST/SET_ARTIST_LIST_IS_LOADING'
}
