export const actionTypes = {
  MERGE_STATE: 'ARTIST/MERGE_STATE',
  CLEAR_STATE: 'ARTIST/CLEAR_STATE',
  SET_BASE_INFO: 'ARTIST/SET_BASE_INFO',
  SET_DESC_INFO: 'ARTIST/SET_DESC_INFO',
  SET_SONG_LIST: 'ARTIST/SET_SONG_LIST',
  SET_SONG_COUNT: 'ARTIST/SET_SONG_COUNT',
  SET_ALBUM_LIST: 'ARTIST/SET_ALBUM_LIST',
  SET_ALBUM_COUNT: 'ARTIST/SET_ALBUM_COUNT',
  SET_MV_LIST: 'ARTIST/SET_MV_LIST',
  SET_MV_COUNT: 'ARTIST/SET_MV_COUNT',
  SET_IS_LOADING: 'ARTIST/SET_IS_LOADING'
}
