export const actionTypes = {
  MERGE_STATE: 'DISCOVER_RECOMD/MERGE_STATE',
  CLEAR_STATE: 'DISCOVER_RECOMD/CLEAR_STATE',
  SET_TOP_BANNER_LIST: 'DISCOVER_RECOMD/SET_TOP_BANNER_LIST',
  SET_HOT_RECOMD_LIST: 'DISCOVER_RECOMD/SET_HOT_RECOMD_LIST',
  SET_NEW_ALBUM_LIST: 'DISCOVER_RECOMD/SET_NEW_ALBUM_LIST',
  SET_RANK_MULTI_LIST: 'DISCOVER_RECOMD/SET_RANK_MULTI_LIST',
  SET_HOT_ARTIST_LIST: 'DISCOVER_RECOMD/SET_HOT_ARTIST_LIST',
  SET_RANK_MULTI_LIST_IS_LOADING: 'DISCOVER_RECOMD/SET_RANK_MULTI_LIST_IS_LOADING'
}
