export const actionTypes = {
  MERGE_STATE: 'DISCOVER_TOPLIST/MERGE_STATE',
  CLEAR_STATE: 'DISCOVER_TOPLIST/CLEAR_STATE',
  SET_CHART_LIST: 'DISCOVER_TOPLIST/SET_CHART_LIST',
  SET_CHART_DETAIL: 'DISCOVER_TOPLIST/SET_CHART_DETAIL',
  SET_SONG_LIST: 'DISCOVER_TOPLIST/SET_SONG_LIST',
  SET_HOT_COMMENT_LIST: 'DISCOVER_TOPLIST/SET_HOT_COMMENT_LIST',
  SET_NEW_COMMENT_LIST: 'DISCOVER_TOPLIST/SET_NEW_COMMENT_LIST',
  SET_NEW_COMMENT_COUNT: 'DISCOVER_TOPLIST/SET_NEW_COMMENT_COUNT',
  SET_CHART_DETAIL_IS_LOADING: 'DISCOVER_TOPLIST/SET_CHART_DETAIL_IS_LOADING',
  SET_SONG_LIST_IS_LOADING: 'DISCOVER_TOPLIST/SET_SONG_LIST_IS_LOADING'
}
