export const actionTypes = {
  MERGE_STATE: 'DISCOVER_SONGSHEET/MERGE_STATE',
  CLEAR_STATE: 'DISCOVER_SONGSHEET/CLEAR_STATE',
  SET_CAT_SUB_LIST: 'DISCOVER_SONGSHEET/SET_CAT_SUB_LIST',
  SET_SONGSHEET_LIST: 'DISCOVER_SONGSHEET/SET_SONGSHEET_LIST',
  SET_SONGSHEET_COUNT: 'DISCOVER_SONGSHEET/SET_SONGSHEET_COUNT',
  SET_SONGSHEET_LIST_IS_LOADING: 'DISCOVER_SONGSHEET/SET_SONGSHEET_LIST_IS_LOADING'
}
