export const actionTypes = {
  MERGE_STATE: 'MV/MERGE_STATE',
  CLEAR_STATE: 'MV/CLEAR_STATE',
  SET_MV_DETAIL: 'MV/SET_MV_DETAIL',
  SET_MV_URL: 'MV/SET_MV_URL',
  SET_HOT_COMMENT_LIST: 'MV/SET_HOT_COMMENT_LIST',
  SET_NEW_COMMENT_LIST: 'MV/SET_NEW_COMMENT_LIST',
  SET_NEW_COMMENT_COUNT: 'MV/SET_NEW_COMMENT_COUNT',
  SET_SIMI_MV_LIST: 'MV/SET_SIMI_MV_LIST',
  SET_MV_DETAIL_IS_LOADING: 'MV/SET_MV_DETAIL_IS_LOADING'
}
