export const actionTypes = {
  MERGE_STATE: 'ALBUM/MERGE_STATE',
  CLEAR_STATE: 'ALBUM/CLEAR_STATE',
  SET_ALBUM_DETAIL: 'ALBUM/SET_ALBUM_DETAIL',
  SET_SONG_LIST: 'ALBUM/SET_SONG_LIST',
  SET_HOT_COMMENT_LIST: 'ALBUM/SET_HOT_COMMENT_LIST',
  SET_NEW_COMMENT_LIST: 'ALBUM/SET_NEW_COMMENT_LIST',
  SET_NEW_COMMENT_COUNT: 'ALBUM/SET_NEW_COMMENT_COUNT',
  SET_RELATED_ALBUM_LIST: 'ALBUM/SET_RELATED_ALBUM_LIST',
  SET_ALBUM_DETAIL_IS_LOADING: 'ALBUM/SET_ALBUM_DETAIL_IS_LOADING'
}
