export const actionTypes = {
  MERGE_STATE: 'DISCOVER_ALBUM/MERGE_STATE',
  CLEAR_STATE: 'DISCOVER_ALBUM/CLEAR_STATE',
  SET_HOT_ALBUM_LIST: 'DISCOVER_ALBUM/SET_HOT_ALBUM_LIST',
  SET_ALL_ALBUM_LIST: 'DISCOVER_ALBUM/SET_ALL_ALBUM_LIST',
  SET_ALL_ALBUM_COUNT: 'DISCOVER_ALBUM/SET_ALL_ALBUM_COUNT',
  SET_ALL_ALBUM_LIST_IS_LOADING: 'DISCOVER_ALBUM/SET_ALL_ALBUM_LIST_IS_LOADING'
}
